# Generated by Django 5.1 on 2024-09-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="Category",
            new_name="category",
        ),
    ]
